services:
  gateway:
    image: tomtoomuch/energia-gateway
    ports:
      - "${GATEWAY_PORT:-3000}:3000"
    env_file:
      - ./.env
    depends_on:
      - ms-python
    restart: unless-stopped

  ms-python:
    image: tomtoomuch/energia-ms-python
    ports:
      - "${PYTHON_PORT:-8000}:8000"
    env_file:
      - .env
    restart: unless-stopped

  ms-python-2:
    image: tomtoomuch/energia-ms-python-2
    ports:
      - "${PYTHON_PORT_2:-8002}:8002"
    env_file:
      - .env
    restart: unless-stopped

  llm:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ./llm:/root/.ollama
    pull_policy: always
    restart: unless-stopped
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '2'

    #     reservations:
    #       cpus: '1'
    # entrypoint: >
    #   /bin/sh -c "
    #   ollama serve & 
    #   sleep 5; 
    #   ollama pull gemma4:e4b; 
    #   wait"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  mcp-server:
    image: energia-mcp-server
    ports:
      - "${PYTHON_PORT_3:-8003}:8003"
    env_file:
      - .env
    restart: unless-stopped