services:
  gateway:
    build: 
      context: ./gateway
      dockerfile: dockerfile
  ms-python:
    build:
      context: ./ms-python
      dockerfile: dockerfile
  ms-python-2:
    build:
      context: ./ms-python-2
      dockerfile: dockerfile
  # llm:
  #   build:
  #     context: ./llm
  #     dockerfile: dockerfile
  mcp-server:
    build:
      context: ./mcp_server
      dockerfile: dockerfile