FROM python:3.12-slim

WORKDIR /mcp

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8003

# CMD ["uvicorn", "server:app", "--host", "0.0.0.0", "--port", "8003" ]
CMD ["python", "server.py"]